name: Format

on:
   pull_request:
      branches: [master]

jobs:
   format:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout changes
           uses: actions/checkout@v3
         - name: Install node
           uses: actions/setup-node@v3
         - name: Install required packages
           run: npm install

         - name: Format all files
           run: npm run format
         - name: Commit formatting changes
           uses: stefanzweifel/git-auto-commit-action@v4
           with:
              commit_message: Apply formatting changes
              branch: ${{ github.head_ref }}
