name: Lint

on:
   pull_request:
      branches: [master]

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout changes
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install required packages
        run: npm install

      - name: Run eslint
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          eslint: true
