name: Format
on:
  pull_request:
    branches: [master]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node
      - run: npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}